title: Azadeh Hashemi
logo: "/images/avatar.png?raw=true"
description: > 
  Lifelong Learner
  <br>
  Machine Learning Scientist
  <br>
  Senior Software Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/azadehhashemi/">View My LinkedIn Profile</a> 
  
  <a href="https://www.linkedin.com/in/azadehhashemi/"><img src="/images/linkedin.png" alt="My LinkedIn Profile" style="width:42px;height:42px;"></a>
  
theme: jekyll-theme-minimal
