title: Azadeh Hashemi
logo: "/images/avatar.png?raw=true"
description: > 
  Lifelong Learner
  <br>
  Machine Learning Scientist
  <br>
  Senior Software Engineer
  <br><br>
  <a href="https://www.linkedin.com/in/azadehhashemi/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
